### ISSUE TITLE
failure to work on aarch64 linux

### ISSUE THREAD

**Issue by masx200** [ezylean/webp#1]
* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

failure to work on aarch64 linux

Linux localhost 4.9.148 #1 SMP PREEMPT Wed Nov 6 19:08:07 CST 2019 aarch64 Android

```
Error: spawn /data/data/com.termux/files/home/long-image-split-square/node_modules/@ezy/webp/lib/libwebp-1.0.3-unsupported/bin/cwebp 

ENOENT                                                   at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)                
                                           at onErrorNT (internal/child_process.js:456:16)                   
at processTicksAndRejections (internal/process/task_queues.js:80:21) 

{                                                            errno: -2,       
                                                 code: 'ENOENT',           
                                        syscall: 'spawn /data/data/com.termux/files/home/long-image-split-square/node_modules/@ezy/webp/lib/libwebp-1.0.3-unsupported/bin/cwebp',          
           path: '/data/data/com.termux/files/home/long-image-split-square/node_modules/@ezy/webp/lib/libwebp-1.0.3-unsupported/bin/cwebp',    
spawnargs: [                      '-o',                                             '/sdcard/sliced-long-pictures/-周叽是可爱兔兔-20200201/00afabe87546768fc847e42c7a29f773_comps-0.webp',                              '--',                                                 '/data/data/com.termux/files/usr/tmp/343f1110-355a-44e6-8d5d-91f81a0f6044.jpg'                                                    ],                                                          
      cmd: '/data/data/com.termux/files/home/long-image-split-square/node_modules/@ezy/webp/lib/libwebp-1.0.3-unsupported/bin/cwebp -o /sdcard/sliced-long-pictures/-周叽是可爱兔 兔-20200201/00afabe87546768fc847e42c7a29f773_comps-0.webp -- /data/data/com.termux/files/usr/tmp/343f1110-355a-44e6-8d5d-91f81a0f6044.jpg'                   }

      error Command failed with exit code 1.

```
* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by didierdemoniere** [comment]
hi @masx200, unfortunately the "libwebp" project release directory do not seem to include a precompiled binary for android see here: http://downloads.webmproject.org/releases/webp/
this package just download the binaries and use the right one depending of the platform and architecture.

**Comment by masx200** [comment]
https://cdn.jsdelivr.net/gh/masx200/long-image-split-square@libwebp-1.1.0-aarch64/libwebp-1.1.0-aarch64.zip

You can download the Linux aarch64 version here
